# Global configuration
global:
  checkNewVersion: true
  sendAnonymousUsage: false

# EntryPoints configuration
entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443

# Traefik logs configuration
log:
  level: ERROR

# API and dashboard configuration
api:
  dashboard: true
  insecure: false

# Docker configuration backend
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

# lets encrypt
certificatesResolvers:
  leproduction:
    acme:
      email: marv@der-marv.de
      caServer: https://acme-v02.api.letsencrypt.org/directory
      storage: /ssl-certs/acme.json
      httpChallenge:
        entryPoint: web
  lestaging:
    acme:
      email: marv@der-marv.de
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      storage: /ssl-certs/acme.json
      httpChallenge:
        entryPoint: web
